[package]
name = "html_parse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forest-ds = { path = "/home/joshuachp/share/repos/github/forest-ds" }
html5ever = "0.26"
indexmap = "1.9"
